spring:
  messages:
    basename: application, errors


  redis:
    host: localhost
    port: 6370
  profiles:
    active: local


  datasource:
    url : jdbc:h2:mem:testdb;
    username : sa
    password :
    driver-class-name : org.h2.Driver


  jpa:
    hibernate:
      use-new-id-generator-mappings : false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: whskwock
    password: naverboard123

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            client-name: Kakao
            client-id : 5119b65b42c4da50a4c3bb23eb9a7dd6
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id





logging level:
  org.hibernate.SQL : debug

admin:
  password: admin123123


file:
  dir: /Users/lim/boardApp/src/main/resources/static/images/

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password: password

junit:
  jupiter:
    extensions:
      autodetection:
        enabled: true