spring:
  messages:
    basename: application, errors
  config:
    import: local.yml

  datasource:
    url :  jdbc:h2:tcp://localhost/~/boardApp
    username : sa
    password : sa
    driver-class-name : org.h2.Driver


  jpa:
    hibernate:
      use-new-id-generator-mappings : false
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true