spring:
  messages:
    basename: application, errors
    config:
      import:


  datasource:
    url :  jdbc:h2:mem:testdb;
    username : sa
    password :
    driver-class-name : org.h2.Driver


  jpa:
    hibernate:
      use-new-id-generator-mappings : false
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: whskwock
    password: naverboard123


logging level:
  org.hibernate.SQL : debug

admin:
  password: admin123123


file:
  dir: /Users/lim/boardApp/src/main/resources/static/images/

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password: password