spring:
  messages:
    basename: application, errors
  config:
    import: local.yml

  datasource:
     url :  jdbc:h2:tcp://localhost/~/boardApp
     username : sa
     password : sa
     driver-class-name : org.h2.Driver

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      use-new-id-generator-mappings : false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jdbc:
    url :

  # Naver smtp server 사용

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id


admin:
  password: admin123123


file:
  dir: /Users/lim/boardApp/src/main/resources/static/images/

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password: password

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug



