spring:
  h2:
    console:
      enabled : true
      path : /h2-console


    datasource:
      url :  jdbc:h2:tcp://localhost/~/test
      username : sa
      password :
      driver-class-name : org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: update  # option type: create, create-drop, update, validate, none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
            show_sql: true  # sql 쿼리를 보여줍니다.
            format_sql: true  # sql query formatting
            use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

    bean:
      id : entityManagerFactory
      class : org.springframework.orm.pa.LocalContainerEntityManagerFactoryBean

logging level:
  org.hibernate.SQL : debug